In [3]:
import pandas as pd

In [4]:
df_qwen = pd.read_csv('D:\\repo\\ie403\\data\\silver\\data_model.csv')

In [5]:
df_qwen.info()

<class 'pandas.DataFrame'>
RangeIndex: 5190 entries, 0 to 5189
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         5190 non-null   int64
 1   comment                    5190 non-null   str
 2   graphics                   5190 non-null   int64
 3   matchmaking                5190 non-null   int64
 4   store & microtransactions  5190 non-null   int64
 5   technical_issue            5190 non-null   int64
 6   mechanics                  5190 non-null   int64
 7   developer_support          5190 non-null   int64
 8   event                      5190 non-null   int64
 9   community                  5190 non-null   int64
 10  hero_design                5190 non-null   int64
 11  difficulty                 5190 non-null   int64
 12  timestamp                  5190 non-null   str
 13  version                    4839 non-null   str
 14  normalized                 5190 non-null   str
 15  svm                        5190 non-null   str
 16  phobert                    5190 non-null   str
 17  qwen                       5190 non-null   str
dtypes: int64(11), str(7)
memory usage: 730.0 KB

In [6]:
df_qwen.head()

,id,comment,graphics,matchmaking,store & microtransactions,technical_issue,mechanics,developer_support,event,community,hero_design,difficulty,timestamp,version,normalized,svm,phobert,qwen
0,1,game thì hút máu vcl,0,0,2,0,0,0,0,0,0,0,2025-03-23 12:18:19,1.57.1.8,game thì hút máu vô cùng,game thì hút máu vô_cùng,game thì hút máu vô_cùng,game thì hút máu vô cùng
1,2,Sao tài khoản garena k vào dc vậy,0,0,0,2,0,0,0,0,0,0,2025-03-16 16:10:02,1.57.1.2,sao tài khoản garena không vào được vậy,sao tài_khoản garena không_vào được vậy,sao tài_khoản garena không vào được vậy,sao tài khoản garena không vào được vậy
2,3,Game mục nát lắm rồi nên xoá khỏi sv việt nam,0,0,0,0,0,0,0,0,0,0,2025-03-12 15:27:43,1.57.1.2,game mục nát lắm rồi nên xóa khỏi server việt nam,game mục_nát lắm rồi nên xóa khỏi server việt_nam,game mục_nát lắm rồi nên xóa khỏi server việt_nam,game mục nát lắm rồi nên xóa khỏi server việt nam
3,4,Như cc ko dăng nhập đc,0,0,0,2,0,0,0,0,0,0,2025-03-04 22:23:20,1.57.1.2,tệ hại không đăng nhập được,tệ_hại không_đăng_nhập được,tệ_hại không đăng_nhập được,tệ hại không đăng nhập được
4,5,Trải nghiệm quá tệ cần fix nhiều lỗi,0,0,0,2,0,2,0,0,0,0,2025-03-08 18:03:24,1.57.1.2,trải nghiệm quá tệ cần fix nhiều lỗi,trải nghiệm quá tệ cần fix nhiều lỗi,trải_nghiệm quá tệ cần fix nhiều lỗi,trải nghiệm quá tệ cần fix nhiều lỗi

In [7]:
df_qwen = df_qwen.drop(columns={'timestamp', 'version', 'normalized', 'svm', 'phobert'})

In [8]:
df_qwen.info()

<class 'pandas.DataFrame'>
RangeIndex: 5190 entries, 0 to 5189
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         5190 non-null   int64
 1   comment                    5190 non-null   str
 2   graphics                   5190 non-null   int64
 3   matchmaking                5190 non-null   int64
 4   store & microtransactions  5190 non-null   int64
 5   technical_issue            5190 non-null   int64
 6   mechanics                  5190 non-null   int64
 7   developer_support          5190 non-null   int64
 8   event                      5190 non-null   int64
 9   community                  5190 non-null   int64
 10  hero_design                5190 non-null   int64
 11  difficulty                 5190 non-null   int64
 12  qwen                       5190 non-null   str
dtypes: int64(11), str(2)
memory usage: 527.2 KB

In [9]:
df_qwen = df_qwen.drop(columns={'comment'})
df_qwen = df_qwen.rename(columns={'qwen':'review'})

In [10]:
df_qwen.info()

<class 'pandas.DataFrame'>
RangeIndex: 5190 entries, 0 to 5189
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         5190 non-null   int64
 1   graphics                   5190 non-null   int64
 2   matchmaking                5190 non-null   int64
 3   store & microtransactions  5190 non-null   int64
 4   technical_issue            5190 non-null   int64
 5   mechanics                  5190 non-null   int64
 6   developer_support          5190 non-null   int64
 7   event                      5190 non-null   int64
 8   community                  5190 non-null   int64
 9   hero_design                5190 non-null   int64
 10  difficulty                 5190 non-null   int64
 11  review                     5190 non-null   str
dtypes: int64(11), str(1)
memory usage: 486.7 KB

In [11]:
df_qwen.to_csv('../../data/gold/qwen_preprocess.csv', index=False)

In [12]:
df_qwen.columns

Index(['id', 'graphics', 'matchmaking', 'store & microtransactions',
       'technical_issue', 'mechanics', 'developer_support', 'event',
       'community', 'hero_design', 'difficulty', 'review'],
      dtype='str')

In [13]:
df_qwen.head(10)

,id,graphics,matchmaking,store & microtransactions,technical_issue,mechanics,developer_support,event,community,hero_design,difficulty,review
0,1,0,0,2,0,0,0,0,0,0,0,game thì hút máu vô cùng
1,2,0,0,0,2,0,0,0,0,0,0,sao tài khoản garena không vào được vậy
2,3,0,0,0,0,0,0,0,0,0,0,game mục nát lắm rồi nên xóa khỏi server việt nam
3,4,0,0,0,2,0,0,0,0,0,0,tệ hại không đăng nhập được
4,5,0,0,0,2,0,2,0,0,0,0,trải nghiệm quá tệ cần fix nhiều lỗi
5,6,0,2,0,0,0,0,0,2,0,0,"game bị tệ hại hả, nghĩ sao 1 trận mvp mà cộng..."
6,7,0,0,0,0,0,0,0,0,0,0,game tệ hại
7,8,0,0,0,0,2,1,0,0,1,0,a gà ơi sao a buff raz quá vậy xin a cân bằng ...
8,9,0,0,0,0,0,1,0,0,0,0,đề nghị xác minh độ tuổi rồi mới cho chơi
9,10,0,0,0,0,0,0,0,0,0,0,game tệ hại vô cùng